input "1267:12447:ELAN1200:00_04F3:309F_Touchpad" {
    tap enabled  # Enable tap-to-click
    dwt disabled # Disable while typing (you can set to disabled for testing)
    natural_scroll disabled  # Set this according to your preference
    scroll_method two_finger  # Keep your scrolling method
    middle_emulation disabled  # Set this as needed
}
