background_opacity 0.70
disable_default_bell
include ~/.config/kitty/themes/Belafonte_Day.conf
font_family JetBrainsMono Nerd Font
#semibold:
#font_family JetBrainsMono Nerd Font Propo

font_size 13.5

