cursor #e0e2e8
cursor_text_color #c2c7cf

foreground            #e0e2e8
background            #101418
selection_foreground  #243240
selection_background  #b9c8da
url_color             #9ccbfb

color0   #101418
color1   #ff729c
color2   #7dfb8e
color3   #fff772
color4   #82b7ee
color5   #234b74
color6   #9ccbfb
color7   #eff7ff
color8   #969ca3
color9   #ff9fbc
color10  #a5ffb1
color11  #fffaa5
color12  #acd5ff
color13  #bbdcff
color14  #d3e9ff
color15  #f8fbff
